const dummyData = {
    // 1. LAS ÁREAS DE EXPERTISE REALES DE MADS (mads.land → "Áreas de expertise")
    categories: [
        { name: "Transformación y Cultura", description: "Procesos de cambio cultural y transformación organizacional." },
        { name: "Bienestar", description: "Programas de bienestar integral para tus equipos." },
        { name: "Agilidad", description: "Metodologías ágiles aplicadas a la gestión de personas." },
        { name: "Comunicación", description: "Estrategias de comunicación interna y employer branding." },
        { name: "Team Buildings", description: "Dinámicas y experiencias para fortalecer al equipo." },
        { name: "Inteligencia Artificial", description: "Adopción de IA aplicada a procesos de RRHH." },
        { name: "DEI", description: "Diversidad, equidad e inclusión en el lugar de trabajo." },
        { name: "Sustentabilidad y RSE", description: "Programas de sustentabilidad y responsabilidad social." },
        { name: "Speakers", description: "Charlas y speakers para eventos corporativos." },
        { name: "Eventos", description: "Producción de eventos internos y corporativos." },
    ],

    // 2. MANTENEMOS ESTA TABLA AUXILIAR PARA QUE EL INYECTOR NO SE ROMPA
    customizations: [
        { name: "Propuesta Express (24hs)", price: 0, type: "topping" },
        { name: "Soporte On-Demand", price: 0, type: "topping" },
        { name: "Consultor Senior Dedicado", price: 0, type: "side" },
    ],

    // 3. LAS ESPECIALIDADES REALES DE MADS, una por área de expertise.
    // No usamos fotos de stock: cada especialidad se renderiza con un ícono +
    // degradado de marca (ver constants/index.ts → getSpecialtyVisual), así evitamos
    // el problema de imágenes que no corresponden al contenido. image_url queda
    // como placeholder inerte, requerido por el esquema de Appwrite pero sin uso visual.
    menu: [
        {
            name: "Diagnóstico y Transformación Cultural",
            description: "Relevamos la cultura actual de tu organización y diseñamos el camino hacia la cultura que necesitás para crecer.",
            image_url: "https://placehold.co/400x400/14B8A6/ffffff.png",
            price: 0.0,
            rating: 5.0,
            calories: 0,
            protein: 0,
            category_name: "Transformación y Cultura",
            customizations: ["Propuesta Express (24hs)"],
        },
        {
            name: "Programas de Bienestar Integral",
            description: "Iniciativas de salud física, mental y emocional para sostener el bienestar de tus equipos.",
            image_url: "https://placehold.co/400x400/4C5FD9/ffffff.png",
            price: 0.0,
            rating: 4.9,
            calories: 0,
            protein: 0,
            category_name: "Bienestar",
            customizations: ["Soporte On-Demand"],
        },
        {
            name: "Transformación Ágil de Equipos",
            description: "Metodologías ágiles y frameworks de trabajo para equipos más rápidos y colaborativos.",
            image_url: "https://placehold.co/400x400/E91E8C/ffffff.png",
            price: 0.0,
            rating: 4.8,
            calories: 0,
            protein: 0,
            category_name: "Agilidad",
            customizations: ["Consultor Senior Dedicado"],
        },
        {
            name: "Comunicación Interna y Employer Branding",
            description: "Estrategias para posicionar a tu empresa como un gran lugar para trabajar, puertas adentro y afuera.",
            image_url: "https://placehold.co/400x400/7C3AED/ffffff.png",
            price: 0.0,
            rating: 4.9,
            calories: 0,
            protein: 0,
            category_name: "Comunicación",
            customizations: ["Propuesta Express (24hs)"],
        },
        {
            name: "Team Buildings & Dinámicas Grupales",
            description: "Experiencias diseñadas para fortalecer los vínculos y la colaboración dentro de tus equipos.",
            image_url: "https://placehold.co/400x400/14B8A6/ffffff.png",
            price: 0.0,
            rating: 4.8,
            calories: 0,
            protein: 0,
            category_name: "Team Buildings",
            customizations: ["Soporte On-Demand"],
        },
        {
            name: "IA Aplicada a Personas",
            description: "Acompañamos la adopción de inteligencia artificial en tus procesos de gestión de talento.",
            image_url: "https://placehold.co/400x400/4C5FD9/ffffff.png",
            price: 0.0,
            rating: 4.7,
            calories: 0,
            protein: 0,
            category_name: "Inteligencia Artificial",
            customizations: ["Consultor Senior Dedicado"],
        },
        {
            name: "Diversidad, Equidad e Inclusión",
            description: "Programas para construir organizaciones más diversas, equitativas e inclusivas.",
            image_url: "https://placehold.co/400x400/E91E8C/ffffff.png",
            price: 0.0,
            rating: 5.0,
            calories: 0,
            protein: 0,
            category_name: "DEI",
            customizations: ["Propuesta Express (24hs)"],
        },
        {
            name: "Sustentabilidad y RSE",
            description: "Diseñamos e implementamos programas de responsabilidad social y sustentabilidad corporativa.",
            image_url: "https://placehold.co/400x400/14B8A6/ffffff.png",
            price: 0.0,
            rating: 4.8,
            calories: 0,
            protein: 0,
            category_name: "Sustentabilidad y RSE",
            customizations: ["Soporte On-Demand"],
        },
        {
            name: "Speakers & Charlas Inspiracionales",
            description: "Charlas disruptivas e inspiracionales para eventos corporativos y lanzamientos.",
            image_url: "https://placehold.co/400x400/7C3AED/ffffff.png",
            price: 0.0,
            rating: 4.9,
            calories: 0,
            protein: 0,
            category_name: "Speakers",
            customizations: ["Consultor Senior Dedicado"],
        },
        {
            name: "Producción de Eventos Corporativos",
            description: "Planificación y producción integral de eventos internos y corporativos.",
            image_url: "https://placehold.co/400x400/E91E8C/ffffff.png",
            price: 0.0,
            rating: 4.9,
            calories: 0,
            protein: 0,
            category_name: "Eventos",
            customizations: ["Propuesta Express (24hs)"],
        },
    ],
};

export default dummyData;
